% Bernoulli Map Chaotic Sequence Generation

clc
clear all

% Parameters
n = 1000; % Number of iterations
x0 = 0.1; % Initial condition
r = 0.7; % Control parameter (0 < r <= 1)

% Preallocate array for the chaotic sequence
chaotic_sequence = zeros(1, n);

% Set the initial value of the sequence
chaotic_sequence(1) = x0;

% Iterate the Bernoulli map
for i = 2:n
    if chaotic_sequence(i-1) < r
        chaotic_sequence(i) = chaotic_sequence(i-1) / r;
    else
        chaotic_sequence(i) = (chaotic_sequence(i-1) - r) / (1 - r);
    end
end

% Compute the mean of the chaotic sequence
sequence_mean = mean(chaotic_sequence);

% Binary quantization based on the mean
binary_sequence = chaotic_sequence > sequence_mean;

% Plot the chaotic sequence
figure;
subplot(2, 1, 1);
plot(chaotic_sequence, '-b');
xlabel('Iteration');
ylabel('Value');
title('Chaotic Sequence Generated by Bernoulli Map');
grid on;

% Plot the binary quantized sequence
subplot(2, 1, 2);
stem(binary_sequence, '-r');
xlabel('Iteration');
ylabel('Binary Value');
title('Binary Quantized Sequence');
grid on;