% Sine Map Chaotic Sequence Generation

% Parameters
n = 1000; % Number of iterations
x0 = 0.5; % Initial condition
r = 0.9; % Control parameter (0 < r <= 1 for chaos)

% Preallocate array for the chaotic sequence
chaotic_sequence = zeros(1, n);

% Set the initial value of the sequence
chaotic_sequence(1) = x0;

% Iterate the Sine map
for i = 2:n
    chaotic_sequence(i) = r * sin(pi * chaotic_sequence(i-1));
end

% Compute the mean of the chaotic sequence
sequence_mean = mean(chaotic_sequence);

% Binary quantization based on the mean
binary_sequence = chaotic_sequence > sequence_mean;

% Plot the chaotic sequence
figure;
subplot(2, 1, 1);
plot(chaotic_sequence, '-b');
xlabel('Iteration');
ylabel('Value');
title('Chaotic Sequence Generated by Sine Map');
grid on;

% Plot the binary quantized sequence
subplot(2, 1, 2);
stem(binary_sequence, '-r');
xlabel('Iteration');
ylabel('Binary Value');
title('Binary Quantized Sequence');
grid on;
